version: '3'

services:
  simple_event_logging:
    image: simple_event_logging:latest
    command: uwsgi /uwsgi.yaml --show-config
    ports:
      - "287:8000"
    volumes:
      - ./src:/src
      - ./data:/src/data
